services:
  webapigateway:
    image: ${DOCKER_REGISTRY-}webapigateway
    build:
      context: .
      dockerfile: WebApiGateway/Dockerfile
    ports:
      - 8001:80
    networks:
      - backend
  postgres_messages:
    image: postgres:latest
    container_name: postgres_messages
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_messages:/var/lib/postgresql/data
    networks:
      - backend
      - messages
  web-api-messages:
    image: rasito/webapimessages:latest
    ports:
      - 8003:8080
    environment:
      DbSettings__Host: postgres_messages
      DbSettings__Port: 5432
      DbSettings__Username: postgres
      DbSettings__Password: postgres
      DbSettings__Database: postgres
      JwtSettings__SecretKey: qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm
    depends_on:
      - postgres_messages
    networks:
      - messages
  auth_database:
    image: postgres:latest
    container_name: database_authentication
    environment:
      POSTGRES_USER: common
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: Authapi
    ports:
      - 5433:5432
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - authentication
  auth_api:
    image: chema00/authapi:latest
    container_name: authentication_api
    environment:
      DbSettings__Host: auth_database
      DbSettings__Port: 5432
      DbSettings__Username: common
      DbSettings__Password: auth
      DbSettings__Database: Authapi
      JwtSettings__SecretKey: qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm
      EmailSettings__UserEmail: noresponsewheelie@gmail.com
      EmailSettings__SmptServer: smtp.gmail.com
      EmailSettings__UserName: noresponsewheelie@gmail.com
      EmailSettings__UserApiKey: dmlhjxymijzmtywx
      EmailSettings__Port: 465
    depends_on:
      - auth_database
    networks:
      - authentication
      - backend
    ports:
      - 8000:8080
  com_database:
    image: postgres:latest
    container_name: database_community
    environment:
      POSTGRES_USER: common
      POSTGRES_PASSWORD: com
      POSTGRES_DB: Comapi
    ports:
      - 5434:5432
    volumes:
      - postgres_com_data:/var/lib/postgresql/data
    networks:
      - communities
  com_api:
    image: chema00/comunapi:latest
    container_name: community_api
    environment:
      DbSettings__Host: com_database
      DbSettings__Port: 5432
      DbSettings__Username: common
      DbSettings__Password: com
      DbSettings__Database: Comapi
      JwtSettings__SecretKey: qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm
    depends_on:
      - com_database
    networks:
      - communities
      - backend
    ports:
      - 8002:8080
  prof_database:
    image: postgres:latest
    container_name: database_prof
    environment:
      POSTGRES_USER: prof
      POSTGRES_PASSWORD: prof
      POSTGRES_DB: Prof
    ports:
      - 5435:5432
    volumes:
      - postgres_prof_data:/var/lib/postgresql/data
    networks:
      - prof
  prof_api:
    image: chema00/profapi:latest
    container_name: prof_api
    environment:
      DbSettings__Host: prof_database
      DbSettings__Port: 5432
      DbSettings__Username: prof
      DbSettings__Password: prof
      DbSettings__Database: Prof
      JwtSettings__SecretKey: qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm
    depends_on:
      - prof_database
    networks:
      - prof
      - backend
    ports:
      - 8004:8080
  rev_database:
    image: postgres:latest
    container_name: database_rev
    environment:
      POSTGRES_USER: rev
      POSTGRES_PASSWORD: rev
      POSTGRES_DB: Rev
    ports:
      - 5436:5432
    volumes:
      - postgres_rev_data:/var/lib/postgresql/data
    networks:
      - rev
  rev_api:
    image: chema00/revapi:latest
    container_name: rev_api
    environment:
      DbSettings__Host: rev_database
      DbSettings__Port: 5432
      DbSettings__Username: rev
      DbSettings__Password: rev
      DbSettings__Database: Rev
      JwtSettings__SecretKey: qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm
    depends_on:
      - rev_database
    networks:
      - rev
      - backend
    ports:
      - 8005:8080
networks:
  backend:
    driver: bridge
  messages:
    driver: bridge
  authentication:
    driver: bridge
  communities:
    driver: bridge
  prof:
    driver: bridge
  rev:
    driver: bridge
volumes:
  postgres_messages:
    driver: local
  postgres_auth_data:
    driver: local
  postgres_com_data:
    driver: local
  postgres_prof_data:
    driver: local
  postgres_rev_data:
    driver: local