services:
  webapigateway:
    image: ${DOCKER_REGISTRY-}webapigateway
    build:
      context: .
      dockerfile: WebApiGateway/Dockerfile
    ports:
      - 8001:80
    networks:
      - backend
  postgres_messages:
    image: postgres:latest
    container_name: postgres_messages
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_messages:/var/lib/postgresql/data
    networks:
      - backend
      - messages
  web-api-messages:
    image: rasito/webapimessages:latest
    ports:
      - 8003:8080
    environment:
      DbSettings__Host: postgres_messages
      DbSettings__Port: 5432
      DbSettings__Username: postgres
      DbSettings__Password: postgres
      DbSettings__Database: postgres
      JwtSettings__SecretKey: qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm
    depends_on:
      - postgres_messages
    networks:
      - messages
  auth_database:
    image: postgres:latest
    container_name: database_authentication
    environment:
      POSTGRES_USER: common
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: Authapi
    ports:
      - 5433:5432
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - auth
  auth_api:
    image: chema00/authapi:latest
    container_name: authentication_api
    environment:
      DbSettings__Host: auth_database
      DbSettings__Port: 5432
      DbSettings__Username: common
      DbSettings__Password: auth
      DbSettings__Database: Authapi
      JwtSettings__SecretKey: qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm
      EmailSettings__UserEmail: noresponsewheelie@gmail.com
      EmailSettings__SmptServer: smtp.gmail.com
      EmailSettings__UserName: noresponsewheelie@gmail.com
      EmailSettings__UserApiKey: dmlhjxymijzmtywx
      EmailSettings__Port: 465
    depends_on:
      - auth_database
    networks:
      - auth
      - backend
    ports:
      - 8000:8080
  com_database:
    image: postgres:latest
    container_name: database_community
    environment:
      POSTGRES_USER: common
      POSTGRES_PASSWORD: com
      POSTGRES_DB: Comapi
    ports:
      - 5434:5432
    volumes:
      - postgres_com_data:/var/lib/postgresql/data
    networks:
      - com
  com_api:
    image: chema00/comunapi:latest
    container_name: community_api
    environment:
      DbSettings__Host: com_database
      DbSettings__Port: 5432
      DbSettings__Username: common
      DbSettings__Password: com
      DbSettings__Database: Comapi
      JwtSettings__SecretKey: qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm
    depends_on:
      - com_database
    networks:
      - com
      - backend
    ports:
      - 8002:8080
networks:
  backend:
    driver: bridge
  messages:
    driver: bridge
  auth:
    driver: bridge
  com:
    driver: bridge
volumes:
  postgres_messages:
    driver: local
  postgres_auth_data:
    driver: local
  postgres_com_data:
    driver: local